# Generated by Django 4.2.23 on 2025-07-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_basemodel_description_basemodel_price'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCars',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.basemodel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
            bases=('base.basemodel',),
        ),
    ]
