# Generated by Django 4.2.23 on 2025-07-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
